apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ${{values.namespace}}

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - secret.yaml

commonLabels:
  app.kubernetes.io/name: ${{values.name}}
  app.kubernetes.io/part-of: ${{values.system}}
  app.kubernetes.io/managed-by: argocd
  three-horizons/horizon: h2

images:
  - name: app-image
    newName: ${{values.registry}}/${{values.name}}
    newTag: latest
