apiVersion: v1
kind: ConfigMap
metadata:
  name: ${{ values.name }}-db-config
  labels:
    app.kubernetes.io/name: ${{ values.name }}
data:
  POSTGRES_DB: ${{ values.databaseName | default(values.name | replace("-", "_")) }}
  POSTGRES_HOST: postgresql.databases.svc.cluster.local
  POSTGRES_PORT: "5432"
