apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
{%- if values.enableIngress %}
  - ingress.yaml
{%- endif %}

commonLabels:
  app.kubernetes.io/name: ${{ values.name }}
  app.kubernetes.io/part-of: three-horizons
